import = [
  "~/.config/alacritty/themes/themes/atom_one_light.toml"
]

[shell]
program = "tmux"
args = [ "new-session", "-A", "-s", "master"]

[window]
padding = { x = 0, y = 0 }
dynamic_padding = true

[font]
normal = { family = "Hasklig" }
size = 13.0

[cursor]
style = { shape = "Block", blinking = "Always" }

[selection]
save_to_clipboard = true
